create table director(
    director_id int primary key GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) not null unique,
    age int check(age > 10)
);


create table movie(
    movie_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_id int NOT NULL references director(director_id),
    name varchar(200) NOT NULL,
    year_of_production int check(year_of_production > 1900)
);


select * from director;

select * from director where director_id = 5;

select director.name, movie.name from director left join movie on director.director_id = movie.director_id;
