create table citizen(
    citizen_id int primary key GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) not null,
    age int not null check(age > 0)
);

create table passport(
    citizen_id int primary key references citizen(citizen_id),
    passport_number int
);



INSERT INTO Citizen(name, age) VALUES ('Bob', 12);
INSERT INTO Citizen(name, age) VALUES ('Tom', 24);
INSERT INTO Citizen(name, age) VALUES ('Katy', 39);
INSERT INTO Citizen(name, age) VALUES ('Alice', 45);

INSERT INTO Passport(citizen_id, passport_number) VALUES (1, 12345);
INSERT INTO Passport(citizen_id, passport_number) VALUES (2, 75124);
INSERT INTO Passport(citizen_id, passport_number) VALUES (3, 91245);
INSERT INTO Passport(citizen_id, passport_number) VALUES (4, 19259);

select citizen.name, passport.passport_number from citizen join passport on citizen.citizen_id = passport.citizen_id;
